### ISSUE TITLE
Max 2015: Py3dsMax doesn't gets initialized

### ISSUE THREAD

**Issue by TheMagSec** [blurstudio/Py3dsMax#2]
The 3dsMax internal Python interpreter is used and I could execute python code with `pymax.exec`, like `pymax.exec("print 5;#[..]")`.
The `MaxPlus` python packages is also working. 

For example:

``` python
pymax.exec("import MaxPLus")   # works fine

pymax.exec("import Py3dsMax") # gives the following error:
```

``` python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Py3dsMax
```

The only thing which is not working is the 'Py3dsMax' package. 
It looks like the `init_module` inside **studiomax_module.cpp** is not executed properly.

I am new to c++ so it's not that easy for me to get through the code. Is there a way to check if `init_module` is executed right?

I just uses the plugin file itself without all the other files which are coming with blur python installer.
In 3dsMax 2015 I also have to initialize the Python interpreter before I load the plugin.
Therefore I uses a simple startup script which looks like this:

```
python.init()
LoadDllsFromDir "PATH_TO_PLUGIN_DIR" "*.dlx"
```

Why is the plugin not adding the module `Py3dsMax` to the interpreter?

I was able to create a _"fake"_ module for `Py3dsMax` inside **python_struct.cpp**:
I implemented the following 3 lines after the struct definition of `pymax`:

``` c++
#include "modsupport.h"
PyMethodDef module_method[]={{ NULL, NULL, 0, NULL }};
PyObject* module = Py_InitModule3( "Py3dsMax", module_method, "Python interface into 3d Studio Max" );
```

But this was only a test for me to see if it would work in general (the **"fake"** module doesn't contains any methods, so it's useless ;) ). 

Thanks

**Comment by MHendricks** [comment]
> Why is the plugin not adding the module Py3dsMax to the interpreter?

Which interpreter maxscript or python? In maxscript you use the struct named pymax, and in python you use the Py3dsMax module. I take it you are compiling it yourself, do you have this problem with the pre-compiled one you can download from the v0.9.0 release? https://github.com/blurstudio/Py3dsMax/releases/tag/v0.9.0

It's pretty rare that you would need to use pymax.exec, I don't think I've used it when I've been working with Py3dsMax. If you just want to run a python script you can use pymax.run "filename". However, the real reason to use Py3dsMax is to get maxscript access to python functions and values, so most of the time you would be using pymax.import "module".

``` maxscript
pymax.exec "import MaxPlus"
OK
maxPlus = pymax.import "MaxPlus"
<module 'MaxPlus' from 'C:\Program Files\Autodesk\3ds Max 2015\MaxPlus.py'>
bi = pymax.import "__builtin__"
<module '__builtin__' (built-in)>
bi.dir(maxPlus)
#("AColor", "AColorList", "AColorList_swigregister", "AColor_AComp", "AColor_CompositeOver", "AColor_swigregister", "AbstractCustomActionItem", "AbstractCustomActionItem_swigregister", "AbstractNotificationHandler", "AbstractNotificationHandler_swigregister", "ActionContext", "ActionContext__CastFrom", "ActionContext_swigregister", "ActionFactory", "ActionItem", "ActionItem__CastFrom", "ActionItem_swigregister", "ActionManager", "ActionManager_FindContext", "ActionManager_GetActionContext", ...)
```

I wish the maxscript listener had a visible prompt. First line is a command, next line is result, repeated. In this code I'm importing the MaxPlus module, and python's built in functions, and listing the attributes of MaxPlus.

I'm also able to import Py3dsMax and get write the hwid to disk.

```
pymax.exec "import sys\nwith open(r'c:\\temp\\stdout.txt', 'w') as sys.stdout:\n    sys.stderr = sys.stdout; import Py3dsMax; print Py3dsMax.GetWindowHandle()"
```

**Comment by pscadding** [comment]
Hi
Thank you for the reply.
I am also working with MagSec-Arts at burrows. Last week I managed to get a working solution, although I'm not sure if its right.

We tried your compiled Py3dsMax release (mentioned above), and had mixed success.

First off we added it to the plugins directory and appended the plugin.ini to use that path. 3dsMax 2015  failed to start, and without error. It only got as far as the splash screen, saying "starting max".

Secondly we tried launching it without loading the plugin on startup and then, loading the plugin post launch through the plugin manager. All the pymax functions caused a `*** System exception ***`. We found we had to run the 3dsmax python.init() first before we could use the pymax functions.

Once we had established that, we were just testing the pymax.exec (we also normally use pymax.run and this had the same error,) with `pymax.exec("import Py3dsMax")`. This however was failing ' with the error `ImportError: No module named Py3dsMax`.

I personally have never written 3ds max plugin, and have very little experience with c++, so consider me a complete beginner with these things.
So we looked at the solution in visual studio, and it appeared that it never seemed to be running the `LibInit()` in the blurPython.cpp, due to it never showing my mprints. After some stumbling around I tried `LibInitialize()` instead, once compiled it, `pymax.exec("import Py3dsMax")` then working inside 3dsmax.

So currently we are in a state where:
1.We still can't have the plugin load on start up using the plugin.ini
2.We have to use the `python.init()` before using any pymax functions.
3. We now have a start up maxscript that runs `python.init()` and then loads the plugin.

We should be able to work with this now, but we wanted to check that our current state is to be expected, and that we are not missing anything.

Thank you very much for all the work you and jjayakumar have done to get this working in 2015, its so frustrating that Autodesk didn't take on using your implementation of python max. Also is this the right place for a ticket, or would you prefer it on source forge?

thanks
Phil

**Comment by MHendricks** [comment]
I don't know if this causes problems, but we are compiling using python 2.7.3 64bit.

http://help.autodesk.com/view/3DSMAX/2015/ENU/?guid=__files_GUID_F93C33D5_E6B6_4353_80A2_91BA9C7B0C54_htm

``` maxscript
python.execute "import sys;print sys.version"
2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]
#success
```

To get this to work I had to temporarily disable Py3dsMax because I was getting this error.

``` maxscript
python.execute "import sys;print sys.version"
-- Runtime error: <type 'exceptions.SystemError'> PyEval_EvalCodeEx: NULL globals
```

That being said, I'm still not getting the same issue you describe.

**Comment by MHendricks** [comment]
https://github.com/blurstudio/Py3dsMax/tree/NULLGlobals

I think the "PyEval_EvalCodeEx: NULL globals" problem is a different symptom of the same problem you are having. In the NULLGlobals branch I have removed the call to Py_Initialize() and Py_Finalize(). I also removed the call to init_module in LibInit. This allows the Py3dsMax plugin to load but not break python.execute. I think the problem has to do with Py3dsMax initializing python before max initializes its python module.

I added a pymax.init() function. This has to be called after python.init() is called or Max will crash because I removed the call to Py_Initialize().

``` maxscript
python.init()
#success
pymax.init()
[blurPython] DLL has been successfully loaded.
OK
python.execute "import sys;print sys.version"
2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]
#success
pymax.exec "import sys;print sys.version"
2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]
OK
pymax.import "Py3dsMax"
<module 'Py3dsMax' (built-in)>
pymax.import "MaxPlus"
<module 'MaxPlus' from 'C:\Program Files\Autodesk\3ds Max 2015\MaxPlus.pyc'>
```

At this point we are left with needing to call python.init() then pymax.init(), which I would like to avoid. I tried calling maxscript inside init_module, but that resulted in a crash.

I wonder if creating a PostLoadCallback will delay the execution long enough that Max has initialized python so we can properly create the Py3dsMax module.

**Comment by TheMagSec** [comment]
We had also some other issues using the integrated Python version from 3ds Max. The biggest issue is, that it looks like, that Max integrated Python interpreter is reset it's environment if `python.executeFile` is used. 

That means former appended path to `sys.path` are no longer available, which is not really useful while working in a pipeline environment. that was the main reason for me to change the plugin and gave it an option to use a different python interpreter next to the internal one from Max. 

The over problem we had with the integrated python interpreter was, that threading is not really working in it's environment. In some cases it was just crashing (python was no longer available inside max) and in others it was running, but only if the mouse pointer is inside the Ui (with Qt thread) and be moved. We had the weirdest results. We running fine for now with an additional external (could be installed local or on the server) python interpreter, but we are still testing it with our pipeline. 

I will post later a link to our forked git repository with our changes and how we managed this issues. 
Before I upload our current version, I want to test your new changes.

Do you have the same problems with threading processes in python and do you also loose the `sys.path` environment when executing a new python file with the internal interpreter (not with `pymax`)??

**Comment by TheMagSec** [comment]
You can find our repository here:
https://github.com/burrowsyr/Py3dsMax

**Comment by MHendricks** [comment]
``` maxscript
python.init()
#success
pymax.init()
[blurPython] DLL has been successfully loaded.
OK
sys = pymax.import "sys"
<module 'sys' (built-in)>
sys.path
#("C:\Program Files\Autodesk\3ds Max 2015\", "C:\Program Files\Autodesk\3ds Max 2015\python", "C:\Program Files\Autodesk\3ds Max 2015\python\Lib", "C:\Program Files\Autodesk\3ds Max 2015\python\DLLs", "C:\Program Files\Autodesk\3ds Max 2015\python\Lib\site-packages", "C:\Users\mikeh\AppData\Local\Autodesk\3dsMax\2015 - 64bit\ENU\scripts\python", "")
pymax.exec @"import sys; sys.path.append(r'c:\temp')"
OK
sys.path
#("C:\Program Files\Autodesk\3ds Max 2015\", "C:\Program Files\Autodesk\3ds Max 2015\python", "C:\Program Files\Autodesk\3ds Max 2015\python\Lib", "C:\Program Files\Autodesk\3ds Max 2015\python\DLLs", "C:\Program Files\Autodesk\3ds Max 2015\python\Lib\site-packages", "C:\Users\mikeh\AppData\Local\Autodesk\3dsMax\2015 - 64bit\ENU\scripts\python", "", "c:\temp")
python.executeFile @"C:\temp\max2015test.py"
Test
#success
sys.path
#("C:\Program Files\Autodesk\3ds Max 2015\", "C:\Program Files\Autodesk\3ds Max 2015\python", "C:\Program Files\Autodesk\3ds Max 2015\python\Lib", "C:\Program Files\Autodesk\3ds Max 2015\python\DLLs", "C:\Program Files\Autodesk\3ds Max 2015\python\Lib\site-packages", "C:\Users\mikeh\AppData\Local\Autodesk\3dsMax\2015 - 64bit\ENU\scripts\python", "")
```

Yes, it looks like `python.executeFile` resets sys.path, which is unfortunate. I haven't run any threading tests, we haven't run into anything yet that needed threading mostly because (we assume) maxscript requires the main thread. 

> [Note that 3ds Max is not thread-safe, so printing to the Listener Window from threads other than the main thread can cause the application to crash, and is not recommended. If you are using multiple threads in your script, you can disconnect sys.stdout and sys.stderr from the Listener using these commands at the beginning of your script:](http://help.autodesk.com/view/3DSMAX/2016/ENU/?guid=__files_GUID_B3FF3632_F177_4A90_AE3D_D36603B7A2F3_htm)

I don't plan on using the python struct as I haven't seen it provide anything we need. I would like to make sure MaxPlus works though, as it may provide something useful. 

We plan on getting PyQt4 to work in max as all of our database bindings are written in sip. Those builds will be made available in the BlurOffsite installers. From testing so far, I'm hopeful our PyQt4 builds for Maya 2015 will work(requiring QtWinMigrate and built using msvc2012) and hopefully we don't need to hack MaxQtBridge.dll/caddies.gup this time, but we haven't gotten that fully tested yet.
